server:
  port: 8082

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m

spring:
  application:
    name: user
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql=true:
    hibernate:
      ddl-auto: none

  datasource:
    username: user-db
    password: kt^#54hfff@%*t53gfhj
    url: jdbc:postgresql://localhost:5432/itmusik
    driver-class-name: org.postgresql.Driver

  main:
    allow-circular-references: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  config:
    import:
      optional:configserver:http://localhost:8888

springdoc:
  api-docs:
    path: /users/v3/api-docs

  swagger-ui:
    path: /users/swagger-ui.html

  endpoints:
    web:
      exposure:
        include: /*

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}