server:
  port: 8084

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m

spring:
  application:
    name: scrobble

  r2dbc:
    password: kt^#54hfff@%*t53gfhj
    username: user-db
    url: r2dbc:postgresql://localhost:5432/itmusik

#  datasource:
#    username: user-db
#    password: kt^#54hfff@%*t53gfhj
#    url: jdbc:postgresql://localhost:5432/itmusik
#    driver-class-name: org.postgresql.Driver

  main:
    allow-circular-references: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}